modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All rights reserved"

[[mods]]
modId = "artsandcrafts"
version = "${version}"
displayName = "Arts & Crafts"
authors = "KekeCreations and Ari"
description = '''
A fabric & forge mod that adds all new decoration features into the game!
'''
#logoFile = ""

[[dependencies.artsandcrafts]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.artsandcrafts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.artsandcrafts]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"