modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"

[[mods]]
modId = "arts_and_crafts"
version = "${version}"
displayName = "Arts & Crafts"
issueTrackerURL = "https://github.com/KekeCreations/Arts-and-Crafts/issues"
updateJSONURL="https://raw.githubusercontent.com/KekeCreations/Arts-and-Crafts/1.20.1x/forge_updates.json"
displayURL="https://kekecreations.boomla.net/minecraft/java-mods/arts-and-crafts"
authors = "KekeCreations and Arbeet!"
description = '''
A fabric & forge mod that adds all new decoration features into the game!
'''
logoFile = "arts_and_crafts_icon.png"

[[dependencies.arts_and_crafts]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arts_and_crafts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
